### ISSUE TITLE
Changing a student status in main does not work anymore

### ISSUE THREAD

**Issue by EWLameijer** [EWLameijer/AttendanceTracker#87]
Query did not return a unique result: 2 results were returned

at nl.itvitae.attendancetracker.attendance.AttendanceRegistrationService.save(AttendanceRegistrationService.java:26) ~[classes/:na]
	at nl.itvitae.attendancetracker.attendance.AttendanceController.register(AttendanceController.java:102) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]

Hypothesis: registering a presence now makes an EXTRA Attendance-object!

**Comment by EWLameijer** [comment]
Fixed
